// Rounded reference values: NASA NSSDCA Planetary Fact Sheet (metric).
export const planets = [
 {id:'mercury',name:'Mercury',kind:'Terrestrial planet',color:'#bcb9b2',diameter:4879,mass:.330,gravity:3.7,distance:57.9,period:88,day:4222.6,temp:167,e:.206,tag:'Small world. Big extremes.',description:'A cratered, rocky world with almost no atmosphere to carry heat from day to night. Mercury races around the Sun while turning slowly on its axis.',fact:'A solar day on Mercury lasts about two Mercury years.',credit:'NASA / Johns Hopkins University Applied Physics Laboratory / Carnegie Institution of Washington'},
 {id:'venus',name:'Venus',kind:'Terrestrial planet',color:'#e5bf83',diameter:12104,mass:4.87,gravity:8.9,distance:108.2,period:224.7,day:2802,temp:464,e:.007,tag:'Our brilliant, inhospitable neighbor.',description:'Under its bright cloud cover, Venus has a crushing carbon dioxide atmosphere. A powerful greenhouse effect makes it hotter than Mercury, despite being farther from the Sun.',fact:'Venus rotates in the opposite direction to most planets.',credit:'NASA / JPL-Caltech'},
 {id:'earth',name:'Earth',kind:'Terrestrial planet',color:'#80c8ee',diameter:12756,mass:5.97,gravity:9.8,distance:149.6,period:365.2,day:24,temp:15,e:.017,tag:'The only home we have ever known.',description:'Liquid water, a protective atmosphere, and a living surface make Earth a remarkable place. Its tilted axis gives us seasons as we travel around the Sun.',fact:'Sunlight takes about eight minutes and twenty seconds to reach Earth.',credit:'NASA / Apollo 17 crew'},
 {id:'mars',name:'Mars',kind:'Terrestrial planet',color:'#e99871',diameter:6792,mass:.642,gravity:3.7,distance:228,period:687,day:24.7,temp:-65,e:.094,tag:'A whole world of what if.',description:'Mars is a cold desert with rusty soil, enormous volcanoes, and evidence that liquid water once flowed across its surface. Its thin atmosphere offers little insulation.',fact:'A day on Mars is only a little longer than a day on Earth.',credit:'NASA / JPL-Caltech'},
 {id:'jupiter',name:'Jupiter',kind:'Gas giant',color:'#dcbaa0',diameter:142984,mass:1898,gravity:23.1,distance:778.5,period:4331,day:9.9,temp:-110,e:.049,tag:'The giant that changes everything.',description:'Jupiter dominates the planets in size and mass. Its cloud bands trace fast winds in a deep atmosphere, while the Great Red Spot is a vast, long-lived storm.',fact:'Jupiter spins once in less than ten hours.',credit:'NASA / JPL-Caltech / SwRI / MSSS'},
 {id:'saturn',name:'Saturn',kind:'Gas giant',color:'#eed5a1',diameter:120536,mass:568,gravity:9,distance:1432,period:10747,day:10.7,temp:-140,e:.052,tag:'Some worlds need no introduction.',description:'A pale gold giant surrounded by rings of countless icy particles. Saturn is an entire system of worlds, from ring-sculpting moons to hazy Titan and ocean-bearing Enceladus.',fact:'Saturn’s average density is lower than that of liquid water.',credit:'NASA / JPL-Caltech / Space Science Institute'},
 {id:'uranus',name:'Uranus',kind:'Ice giant',color:'#a4e3e7',diameter:51118,mass:86.8,gravity:8.7,distance:2867,period:30589,day:17.2,temp:-195,e:.047,tag:'A world turned on its side.',description:'Uranus rolls around the Sun with an extreme axial tilt. Methane in its atmosphere absorbs red light, contributing to the planet’s pale blue-green appearance.',fact:'Its axis is tilted by about 98 degrees relative to its orbital upright.',credit:'NASA / JPL-Caltech'},
 {id:'neptune',name:'Neptune',kind:'Ice giant',color:'#729aef',diameter:49528,mass:102,gravity:11,distance:4515,period:59800,day:16.1,temp:-200,e:.010,tag:'At the edge of the planetary realm.',description:'Neptune is a cold, windy ice giant far beyond the warmth of the inner solar system. It was found after calculations predicted where an unseen planet should be.',fact:'One orbit around the Sun takes roughly 164 Earth years.',credit:'NASA / JPL-Caltech; Voyager 2 (processed color)'}
];
export const byId = id => planets.find(p=>p.id===id);
