import * as s from './science.mjs';
const f=s.fmt;
const circle=(x,y,r,fill,extra='')=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${fill}" ${extra}/>`;
const text=(x,y,t,extra='')=>`<text x="${x}" y="${y}" ${extra}>${t}</text>`;
const line=(x1,y1,x2,y2,extra='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#506983" ${extra}/>`;
const stars=Array.from({length:35},(_,i)=>circle((i*131+23)%620,(i*79+13)%300,i%4===0?1.1:.6,'#9eb9d0','opacity=".45"')).join('');
const svg=(label,body)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 340" role="img" aria-label="${label}"><defs><radialGradient id="sun"><stop stop-color="#fff6d5"/><stop offset=".5" stop-color="#ffd392"/><stop offset="1" stop-color="#d89140"/></radialGradient><radialGradient id="blue"><stop stop-color="#d0f4ff"/><stop offset=".5" stop-color="#7ec7e7"/><stop offset="1" stop-color="#285575"/></radialGradient></defs>${stars}${body}</svg>`;
export function render(id,v,unit='au'){
 let body='',metrics=[],worked='',label='Astronomy model';
 if(id==='orbit-simulator'){
 const r=s.orbit(v.a,v.e,v.mass,v.phase),scale=230/v.a,cx=320,cy=155,sx=cx+230*v.e;
 body=`<ellipse cx="${cx}" cy="${cy}" rx="230" ry="${230*Math.sqrt(1-v.e*v.e)*.58}" fill="none" stroke="#6a8ca9" stroke-width="1.5" stroke-dasharray="4 5"/>${line(sx,cy,sx+r.x*scale,cy-r.y*scale*.58,'stroke-dasharray="3 5"')}${circle(sx,cy,14,'url(#sun)')}${circle(sx+r.x*scale,cy-r.y*scale*.58,8,'url(#blue)')}${text(320,313,'Orbital plane · display tilted for readability','text-anchor="middle"')}`;
 metrics=[['Orbital period',`${f(r.period)} years`],['Current speed',`${f(r.speed)} km/s`],['Star distance',`${f(r.r)} AU`]];worked=`P = √(${f(v.a)}³ / ${f(v.mass)}) = ${f(r.period)} years. Closest approach: ${f(r.near)} AU; farthest: ${f(r.far)} AU.`;label='Elliptical orbit with star at one focus and moving planet';
 } else if(id==='moon-phases'){
 const r=s.moon(v.age),angle=2*Math.PI*r.fraction,R=105,cx=320,cy=147;
 body=circle(cx,cy,R,'#253144');
 for(let y=-R;y<R;y+=1){const extent=Math.sqrt(Math.max(0,R*R-(y+.5)**2)),boundary=Math.cos(angle)*extent;const left=r.fraction<=.5?boundary:-extent,right=r.fraction<=.5?extent:-boundary;body+=`<rect x="${cx+left}" y="${cy+y}" width="${Math.max(0,right-left)}" height="1.1" fill="#e0e7ee"/>`;}
 body+=text(320,295,r.name,'text-anchor="middle" style="font-size:22px"');metrics=[['Illuminated',`${f(r.illumination*100,1)}%`],['Lunar age',`${f(r.age)} days`],['Cycle length','29.53 days']];worked=`(1 − cos(2π × ${f(r.age)} / 29.53059)) / 2 = ${f(r.illumination*100,1)}% illuminated.`;label=`${r.name}, ${f(r.illumination*100,1)} percent illuminated`;
 } else if(id==='gravity-calculator'){
 const r=s.gravity(v.mass,v.radius,v.body);body=circle(320,158,Math.min(110,50+20*Math.log2(v.radius+1)),'url(#blue)')+line(320,38,320,111,'stroke="#e5b777" stroke-width="2"')+`<path d="M312 97 L320 111 L328 97" fill="none" stroke="#e5b777" stroke-width="2"/>`+text(320,296,`Your mass remains ${f(v.body)} kg`,'text-anchor="middle"');metrics=[['Surface gravity',`${f(r.g)} m/s²`],['Your weight',`${f(r.weight)} N`],['Escape speed',`${f(r.escape)} km/s`]];worked=`At ${f(v.mass)} Earth masses and ${f(v.radius)} Earth radii: weight = ${f(v.body)} kg × ${f(r.g)} m/s² = ${f(r.weight)} N.`;label='Planet with arrow showing gravitational attraction';
 } else if(id==='light-travel'){
 const r=s.light(v.distance,unit);body=line(95,140,550,140,'stroke="#e5b777" stroke-width="2" stroke-dasharray="4 6"')+circle(95,140,31,'url(#sun)')+circle(550,140,18,'url(#blue)')+text(95,200,'Source','text-anchor="middle"')+text(550,200,'Observer','text-anchor="middle"')+text(320,110,`${f(v.distance)} ${unit.toUpperCase()}`,'text-anchor="middle" style="fill:#e5b777;font-size:22px"')+text(320,290,'Distance compressed · light speed stays constant','text-anchor="middle"');metrics=[['Light travel',`${f(r.seconds)} s`],['In minutes',`${f(r.seconds/60)} min`],['In years',`${f(r.years,6)} years`]];worked=`${f(r.km)} km ÷ 299,792.458 km/s = ${f(r.seconds)} seconds (${f(r.seconds/86400)} days).`;label='Light travelling between a source and observer';
 } else if(id==='star-lab'){
 const r=s.star(v.temp,v.radius),rad=35+18*Math.log2(v.radius+1);body=circle(320,145,rad+15,r.color,'opacity=".08"')+circle(320,145,rad+6,r.color,'opacity=".14"')+circle(320,145,rad,r.color)+text(320,300,`${f(v.temp,0)} K · illustrative color`,'text-anchor="middle"');metrics=[['Luminosity',`${f(r.luminosity)} Suns`],['Peak wavelength',`${f(r.peak,0)} nm`],['Radius',`${f(v.radius)} Suns`]];worked=`L / L☉ = ${f(v.radius)}² × (${f(v.temp,0)} / 5772)⁴ = ${f(r.luminosity)}. Wien peak = 2,897,772 / ${f(v.temp,0)} = ${f(r.peak)} nm.`;label='Star color and size illustration';
 } else if(id==='telescope-calculator'){
 const r=s.telescope(v.focal,v.eyepiece,v.aperture,v.field);const moonRadius=105*.5/r.field;body=`<defs><clipPath id="scope"><circle cx="320" cy="148" r="105"/></clipPath></defs>${circle(320,148,105,'#050b13','stroke="#677e98" stroke-width="2"')}<g clip-path="url(#scope)">${circle(320,148,moonRadius,'#d4dce6')}${circle(320-moonRadius*.3,148-moonRadius*.35,moonRadius*.18,'#9daaba')}${circle(320+moonRadius*.28,148+moonRadius*.3,moonRadius*.12,'#acb8c6')}</g>${text(320,295,'Moon ≈ 0.5° · centered eyepiece view','text-anchor="middle"')}`;metrics=[['Magnification',`${f(r.power)}×`],['True field',`${f(r.field)}°`],['Exit pupil',`${f(r.exit)} mm`]];worked=`${f(v.focal)} / ${f(v.eyepiece)} = ${f(r.power)}×. Approximate true field: ${f(v.field)}° / ${f(r.power)} = ${f(r.field)}°. Dawes’ resolution estimate: ${f(r.resolution)} arcseconds.`;label='Circular telescope field with approximate Moon size';
 } else if(id==='exoplanet-transit'){
 const r=s.transit(v.planet,v.star,v.impact),R=50,x=v.position/100*1.5,y=v.impact;const depth=s.overlap(1,r.ratio,Math.hypot(x,y))/Math.PI;body=circle(320,133,R,'url(#sun)')+line(160,133-y*R,480,133-y*R,'stroke-dasharray="3 6"')+circle(320+x*R,133-y*R,r.ratio*R,'#050a13','stroke="#6c819a" stroke-width="1"');let path='';for(let i=0;i<=180;i++){let xx=-2.25+i/40,d=s.overlap(1,r.ratio,Math.hypot(xx,y))/Math.PI;path+=`${i?'L':'M'}${95+i*2.5},${245+70*d/Math.max(r.depth/100,.00001)} `;}body+=line(95,245,545,245,'stroke-dasharray="3 5"')+`<path d="${path}" fill="none" stroke="#a2e3f5" stroke-width="2"/>`+circle(320+x*100,245+70*depth/Math.max(r.depth/100,.00001),4,'#e5b777')+text(320,335,'Light curve · dip depth vertically enlarged','text-anchor="middle"');metrics=[['Maximum depth',`${f(r.depth,4)}%`],['Light received',`${f((1-depth)*100,4)}%`],['Radius ratio',f(r.ratio,4)]];worked=`Planet/star radius = ${f(r.ratio,4)}. Central full-overlap depth would be ${f(r.ratio**2*100,4)}%; the chosen path gives a maximum ${f(r.depth,4)}% dip.`;label='Planet crossing a star and its corresponding light curve';
 } else if(id==='stellar-parallax'){
 const r=s.parallax(v.angle);body=`<ellipse cx="320" cy="267" rx="165" ry="26" fill="none" stroke="#526983" stroke-dasharray="4 5"/>${circle(320,267,12,'url(#sun)')}${circle(155,267,8,'url(#blue)')}${circle(485,267,8,'url(#blue)')}${circle(320,60,7,'#fff1d0')}${line(155,267,320,60)}${line(485,267,320,60)}${line(320,267,320,60,'stroke-dasharray="4 6"')}${text(340,145,`p = ${f(v.angle,3)}″`)}${text(320,322,'Earth, six months apart · angle exaggerated','text-anchor="middle"')}`;metrics=[['Distance',`${f(r.parsecs)} pc`],['Light travel',`${f(r.lightyears)} years`],['Parallax',`${f(v.angle,3)}″`]];worked=`1 / ${f(v.angle,3)} arcseconds = ${f(r.parsecs)} parsecs = ${f(r.lightyears)} light-years.`;label='Triangular geometry of stellar parallax using two Earth positions';
 } else if(id==='black-hole-radius'){
 const r=s.blackhole(v.mass),R=53+5*Math.log10(v.mass);body=circle(320,148,R+12,'#d9995b','opacity=".12"')+circle(320,148,R+4,'none','stroke="#e6b47b" stroke-width="3"')+circle(320,148,R,'#010306')+line(320,148,320+R,148,'stroke="#a2e3f5"')+text(320+R+12,153,'rₛ')+text(320,294,'Non-rotating black hole · schematic, not a photograph','text-anchor="middle"');metrics=[['Horizon radius',`${f(r.radius)} km`],['Horizon diameter',`${f(2*r.radius)} km`],['Mass',`${f(v.mass)} Suns`]];worked=`rₛ = 2GM/c² ≈ 2.95334 km × ${f(v.mass)} solar masses = ${f(r.radius)} km.`;label='Black hole event horizon with radius marked';
 } else if(id==='magnitude-comparison'){
 const r=s.magnitude(v.first,v.second);const a=15+65*(30-v.first)/57,b=15+65*(30-v.second)/57;body=circle(205,150,a,'#d1ecff')+circle(445,150,b,'#d1ecff')+text(205,260,`A · ${f(v.first)} mag`,'text-anchor="middle"')+text(445,260,`B · ${f(v.second)} mag`,'text-anchor="middle"')+text(320,318,'Symbol sizes compressed; compare numerical flux ratio','text-anchor="middle"');metrics=[['Flux A / Flux B',`${f(r.ratio)}×`],['Magnitude difference',`${f(v.second-v.first)} mag`],['Brighter object',v.first===v.second?'Equal':v.first<v.second?'Object A':'Object B']];worked=`10^(0.4 × (${f(v.second)} − ${f(v.first)})) = ${f(r.ratio)}. Object A delivers ${f(r.ratio)} times the flux of object B in the same band.`;label='Two stars illustrating relative apparent brightness';
 }
 return {svg:svg(label,body),metrics,worked};
}
