export const AU=149597870.7, C=299792.458, YEAR=365.25*86400, G=6.67430e-11, SOLAR_MASS=1.98847e30, SOLAR_RADIUS=695700;
export function positive(n,name='Value'){if(!Number.isFinite(n)||n<=0)throw new Error(`${name} must be greater than zero.`);return n;}
export const fmt=(n,d=2)=>Math.abs(n)>=1e8||Math.abs(n)>0&&Math.abs(n)<.001?n.toExponential(2):n.toLocaleString('en-US',{maximumFractionDigits:d});
export function orbit(a,e,m,phase){positive(a);positive(m);if(!Number.isFinite(e)||e<0||e>=1)throw new Error('Eccentricity must be between 0 and 1.');if(!Number.isFinite(phase))throw new Error('Phase must be finite.');const M=phase/100*2*Math.PI;let E=M;for(let i=0;i<30;i++)E-=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));const r=a*(1-e*Math.cos(E));return {period:Math.sqrt(a**3/m),near:a*(1-e),far:a*(1+e),r,x:a*(Math.cos(E)-e),y:a*Math.sqrt(1-e*e)*Math.sin(E),speed:Math.sqrt(G*SOLAR_MASS*m*(2/(r*AU*1000)-1/(a*AU*1000)))/1000};}
export function moon(age){if(!Number.isFinite(age))throw new Error('Age must be finite.');const cycle=29.530588853;age=((age%cycle)+cycle)%cycle;const fraction=age/cycle;const names=['New Moon','Waxing crescent','First quarter','Waxing gibbous','Full Moon','Waning gibbous','Last quarter','Waning crescent'];return {age,fraction,illumination:(1-Math.cos(fraction*2*Math.PI))/2,name:names[Math.round(fraction*8)%8]};}
export function moonAge(date){const stamp=new Date(date).getTime();if(!Number.isFinite(stamp))throw new Error('Choose a valid date.');return moon((stamp-Date.UTC(2000,0,6,18,14))/86400000).age;}
export function gravity(mass,radius,bodyMass=1){positive(mass);positive(radius);positive(bodyMass);const g=G*mass*5.9722e24/(radius*6371000)**2;return {g,weight:g*bodyMass,escape:Math.sqrt(2*g*radius*6371000)/1000};}
export function light(distance,unit='au'){positive(distance);const factors={au:AU,km:1,ly:C*YEAR,pc:C*YEAR*3.261563777};if(!(unit in factors))throw new Error('Unknown unit.');const km=distance*factors[unit];return {km,seconds:km/C,years:km/C/YEAR,au:km/AU};}
export function star(temp,radius){positive(temp);positive(radius);return {peak:2.897771955e6/temp,luminosity:radius**2*(temp/5772)**4,color:temp<4000?'#ffac78':temp<5500?'#ffd3a3':temp<7500?'#fff2d5':temp<12000?'#c6e4ff':'#91baff'};}
export function telescope(focal,eyepiece,aperture,field){[focal,eyepiece,aperture,field].forEach(n=>positive(n));const power=focal/eyepiece;return {power,exit:aperture/power,field:field/power,resolution:116/aperture};}
export function transit(planetRadius,starRadius,impact){positive(planetRadius);positive(starRadius);if(!Number.isFinite(impact)||impact<0)throw new Error('Impact must be nonnegative.');const k=planetRadius*6371/(starRadius*SOLAR_RADIUS);return {ratio:k,depth:overlap(1,k,impact)/Math.PI*100};}
export function overlap(R,r,d){if(d>=R+r)return 0;if(d<=Math.abs(R-r))return Math.PI*Math.min(R,r)**2;return R*R*Math.acos((d*d+R*R-r*r)/(2*d*R))+r*r*Math.acos((d*d+r*r-R*R)/(2*d*r))-.5*Math.sqrt((-d+R+r)*(d+R-r)*(d-R+r)*(d+R+r));}
export function parallax(p){positive(p);return {parsecs:1/p,lightyears:3.261563777/p};}
export function blackhole(m){positive(m);return {radius:2*G*SOLAR_MASS*m/(C*1000)**2/1000};}
export function magnitude(m1,m2){if(!Number.isFinite(m1)||!Number.isFinite(m2))throw new Error('Magnitudes must be finite.');return {ratio:10**(.4*(m2-m1))};}
