import {API,searchUrl,normalizeResults,normalizeAssets,nasaJson} from '../lib/nasa-library.mjs';
const $=<T extends Element=HTMLElement>(id:string)=>document.querySelector<T>(`#${id}`)!;
const form=$<HTMLFormElement>('library-search'),query=$<HTMLInputElement>('library-query'),grid=$('library-grid'),status=$('library-status'),notice=$('library-notice'),message=$('library-message'),retry=$<HTMLButtonElement>('library-retry');
const prev=$<HTMLButtonElement>('library-prev'),next=$<HTMLButtonElement>('library-next'),pager=document.querySelector<HTMLElement>('.library-pagination')!;
const dialog=$<HTMLDialogElement>('image-dialog'),preview=$<HTMLImageElement>('image-preview'),original=$<HTMLAnchorElement>('image-original'),source=$<HTMLAnchorElement>('image-source');
let page=1,term='nebula',searchController:AbortController|undefined,assetController:AbortController|undefined,requestId=0,detailId=0,lastTrigger:HTMLElement|null=null;
const cache=new Map<string,ReturnType<typeof normalizeResults>>();
function plain(value:string){const doc=new DOMParser().parseFromString(value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,''),'text/html');doc.querySelectorAll('script,style').forEach(el=>el.remove());return doc.body.textContent?.trim()||'';}
function dateLabel(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'Date not supplied':date.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'});}
function setLocation(){const url=new URL(location.href);url.search='';url.searchParams.set('q',term);if(page>1)url.searchParams.set('page',String(page));if(url.href!==location.href)history.pushState(null,'',url);}
function fromLocation(){const params=new URLSearchParams(location.search);term=(params.get('q')||'nebula').trim().slice(0,160)||'nebula';const p=Number(params.get('page')||1);page=Number.isSafeInteger(p)&&p>0&&p<=10000?p:1;query.value=term;}
function textEl(tag:string,value:string,className=''){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;return el;}
function card(item:ReturnType<typeof normalizeResults>['items'][number]){const b=document.createElement('button');b.type='button';b.className='archive-card';const title=plain(item.title);b.setAttribute('aria-label',`View ${title}`);const media=document.createElement('span');media.className='archive-card-media';const im=document.createElement('img');im.src=item.preview!;im.alt='';im.loading='lazy';im.decoding='async';im.addEventListener('error',()=>{im.hidden=true;media.append(textEl('span','Preview unavailable · open image details','archive-image-error'));},{once:true});media.append(im);const copy=document.createElement('span');copy.className='archive-card-copy';copy.append(textEl('span',`${item.center||'NASA'} · ${dateLabel(item.date)}`,'archive-card-meta'),textEl('span',title,'archive-card-title'),textEl('span','View image & story ↗','archive-card-open'));b.append(media,copy);b.addEventListener('click',()=>openImage(item,b));return b;}
async function search(focus=false){
 searchController?.abort();const controller=new AbortController();searchController=controller;const id=++requestId;const timeout=setTimeout(()=>controller.abort(),15000);
 grid.setAttribute('aria-busy','true');grid.replaceChildren(...Array.from({length:6},()=>{const el=document.createElement('div');el.className='archive-skeleton';el.setAttribute('aria-hidden','true');return el;}));notice.hidden=true;pager.hidden=true;status.textContent='Searching NASA’s archive…';$('library-heading').textContent=`Images for “${term}”`;
 document.querySelectorAll<HTMLElement>('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.topic===term.toLowerCase())));
 try{
 const key=`${term.toLowerCase()}:${page}`;let result=cache.get(key);if(!result){result=normalizeResults(await nasaJson(searchUrl(term,page),controller.signal));if(id!==requestId)return;if(cache.size>=10)cache.delete(cache.keys().next().value!);cache.set(key,result);}
 if(id!==requestId)return;grid.replaceChildren(...result.items.map(card));status.textContent=`${result.total.toLocaleString('en-US')} matching images · ${result.items.length} on this page`;
 if(!result.items.length){notice.hidden=false;message.textContent=page>1?'No images on this page. Go back a page or try a new search.':'No images found. Try a broader term, such as “galaxy”, “Moon”, or “Apollo”.';retry.hidden=true;}
 prev.disabled=page<=1;next.disabled=!result.hasNext;pager.hidden=page===1&&!result.hasNext;$('library-page-label').textContent=`Page ${page}`;
 if(focus){$('library-heading').focus({preventScroll:true});$('library-heading').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 }catch(error){if(id!==requestId)return;grid.replaceChildren();notice.hidden=false;retry.hidden=false;message.textContent=controller.signal.aborted?'The connection to NASA took too long. Please try again.':error instanceof TypeError?'Couldn’t connect to NASA. Check your connection and try again.':error instanceof Error?error.message:'Couldn’t load the archive. Please try again.';status.textContent='Images are temporarily unavailable.';}
 finally{clearTimeout(timeout);if(id===requestId)grid.setAttribute('aria-busy','false');}
}
async function openImage(item:ReturnType<typeof normalizeResults>['items'][number],trigger:HTMLElement){
 assetController?.abort();const controller=new AbortController();assetController=controller;const id=++detailId;const timeout=setTimeout(()=>controller.abort(),15000);lastTrigger=trigger;
 $('image-title').textContent=plain(item.title);$('image-date').textContent=dateLabel(item.date);$('image-description').textContent=plain(item.description)||'NASA has not supplied a description for this image.';$('image-credit').textContent=`${item.credit?`Creator: ${plain(item.credit)} · `:''}NASA center: ${item.center||'Not supplied'} · ID: ${item.id}`;
 $('image-keywords').replaceChildren(...item.keywords.map(k=>textEl('span',plain(k))));original.hidden=true;original.removeAttribute('href');source.href=`https://images.nasa.gov/details/${encodeURIComponent(item.id)}`;
 $('image-error').hidden=true;preview.hidden=false;preview.alt=plain(item.title);preview.src=item.preview!;preview.onerror=()=>{preview.hidden=true;$('image-error').hidden=false;};$('image-asset-status').textContent='Finding the larger image and original file…';dialog.showModal();dialog.scrollTop=0;
 try{const assets=normalizeAssets(await nasaJson(`${API}/asset/${encodeURIComponent(item.id)}`,controller.signal));if(id!==detailId||!dialog.open)return;
 if(assets.preview){preview.onerror=()=>{preview.onerror=()=>{preview.hidden=true;$('image-error').hidden=false;};preview.src=item.preview!;};preview.src=assets.preview;}
 if(assets.original){original.href=assets.original;original.hidden=false;$('image-asset-status').textContent='Original file opens directly from NASA in a new tab.';}else $('image-asset-status').textContent='No original image file was listed. Visit the NASA record for available files.';
 }catch{if(id===detailId&&dialog.open)$('image-asset-status').textContent='The original file list couldn’t load. Visit the NASA record to find available downloads.';}
 finally{clearTimeout(timeout);}
}
$('image-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{detailId++;assetController?.abort();lastTrigger?.focus();});
form.addEventListener('submit',event=>{event.preventDefault();const value=query.value.trim();if(!value){query.value='';query.reportValidity();return;}term=value.slice(0,160);page=1;setLocation();search();});
document.querySelectorAll<HTMLButtonElement>('[data-topic]').forEach(b=>b.addEventListener('click',()=>{term=b.dataset.topic!;page=1;query.value=term;setLocation();search();}));
prev.addEventListener('click',()=>{if(page<=1)return;page--;setLocation();search(true);});next.addEventListener('click',()=>{page++;setLocation();search(true);});retry.addEventListener('click',()=>search());
window.addEventListener('popstate',()=>{if(dialog.open)dialog.close();fromLocation();search();});window.addEventListener('pagehide',()=>{searchController?.abort();assetController?.abort();},{once:true});fromLocation();search();
